version: '3.9'

services:
  blogs-svc:
    build:
      context: .
      dockerfile: mkdocs_blogs.Dockerfile
    ports:
      - "8000:8000"
    restart: "unless-stopped"
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 50M
        reservations:
          cpus: '0.5'
          memory: 20M