name: 🪲 Sample Issue Template
description: Use this template to report issues.
title: "[Issue] <Add a brief title for the issue>"
labels: [🪲 Bug]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this problem?
    description: Please check if a similar issue has already been reported.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Describe the Current Behavior
    description: A clear and concise description of what is currently happening.
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe the Expected Behavior
    description: A clear and concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Detailed steps to reproduce the issue.
    placeholder: |
      1. Navigate to...
      2. Click on...
      3. See the error...
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional Information
    description: |
      Provide any additional context, relevant links, or references.
      
      You can also attach images or log files by dragging and dropping them here.
  validations:
    required: false
- type: checkboxes
  attributes:
    label: Affected Browsers
    description: Select the browsers where you've observed the issue.
    options:
      - Firefox
      - Chrome
      - Safari
      - Microsoft Edge
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment Information (Optional)
    description: Include information about your operating system, device, or other relevant details.
  validations:
    required: false
- type: textarea
  attributes:
    label: Mention Merge Request (Optional)
    description: If this issue is related to a specific merge request or pull request, please mention it here.
  validations:
    required: false
- type: dropdown
  attributes:
    label: Label(s)
    description: Select one or more labels for this issue.
    options:
      - 🪲 bug
      - ✨ enhancement
      - 📃 documentation
      - 🙌🏻 help wanted
      - 🧩 experiment
      - ➕1️⃣ good first issue
  validations:
    required: false
    multiple: true