# Project information
site_name: TuxTechBlogs
site_description: Computer Science Realted Documents And Interview Tips, Questions, Tech-blogs.
site_url: https://github.com/TuxTechLab/Blogs
site_author: Arindam Tanti

# Repository
repo_name: TuxTechLab/Blogs
repo_url: https://github.com/TuxTechLab/Blogs
edit_uri: ''

# Copyright
copyright: Copyright &copy; <a href="http://github.com/TuxTechLab">TuxTechLabs</a> 2023 - 2024

# Configuration
theme:
    name: material
    highlightjs: true
    hljs_languages:
      - yaml
      - rust
    shortcuts:
        help: 191    # ?
        next: 78     # n
        previous: 80 # p
        search: 83   # s
    logo: img/favicon.ico
    favicon: img/favicon.ico
    font:
      text: Roboto
      code: Roboto Mono
    icon:
      logo: fontawesome/solid/code
      repo: fontawesome/brands/github
    features:
      - navigation.expand
      - navigation.top
      - navigation.footer
      - search.highlight
      - search.suggest
      - content.code.copy
    palette:
      # Light mode
      - media: '(prefers-color-scheme: light)'
        scheme: default
        primary: yellow
        accent: light blue
        toggle:
          icon: material/weather-night
          name: Switch to Dark Mode
      # Dark mode
      - media: '(prefers-color-scheme: dark)'
        scheme: slate
        primary: yellow
        accent: amber
        toggle:
          icon: material/weather-sunny
          name: Switch To Light Mode

nav:
  - Start: index.md
  - Code Of Conduct: CODE_OF_CONDUCT.md
  - Contribution Guide: Contribution.md
  - Agile:
    - Introduction: topic/1.0. Agile/00. Introduction.md
    - Understanding the four values of agile: topic/1.0. Agile/01. Understanding the four values of agile.md
    - Using agile in everyday work: topic/1.0. Agile/02. Using agile in everyday work.md
  - ITSM:
    - Introduction: topic/09. ITSM/00. Introduction.md
    - Key Terms: topic/9.0. ITSM/01. Key Terms.md
    - ITSM Library and Practices: topic/09. ITSM/02. ITSM Library and Practices.md
    - Core ITSM Practices: topic/9.0. ITSM/03. Core ITSM Practices.md
    - Maturity Matters: topic/9.0. ITSM/04. Maturity Matters.md
    - The Atlassian ITSM Solution: topic/9.0. ITSM/05. The Atlassian ITSM Solution.md
    - Key Takeaways: topic/9.0. ITSM/06. Key Takeaways.md
  - Scrum:
    - Introduction: topic/19.0. Scrum/00. Introduction.md
    - Scrum With Jira: topic/19.0. Scrum/02. Scrum With Jira.md
  - Management:
    - Run Effective Meetings:
      - Introduction: topic/13.1. Management/00. Run Effective Meetings/01. Introduction.md
      - Event Determination: topic/13.1. Management/00. Run Effective Meetings/02. Event Determination.md
      - Running Effective Meeting: topic/13.1. Management/00. Run Effective Meetings/03. Running Effective Meeting.md
      - Preparation: topic/13.1. Management/00. Run Effective Meetings/04. Preparation.md
      - Facilitation: topic/13.1. Management/00. Run Effective Meetings/05. Facilitation.md
      - Participation: topic/13.1. Management/00. Run Effective Meetings/06. Participation.md
      - Follow-up: topic/13.1. Management/00. Run Effective Meetings/07. Follow-up.md
  - Miscellaneous:
    - Acronyms: topic/acronym.md
    - Ports: topic/ports.md
    - Status Codes: topic/status_codes.md


# Customization   
extra:
  consent:
    title: Cookie consent
    description:
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  social:
    - icon: fontawesome/brands/github
      link: https://github.sprcom/tuxtechlab
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/arindam_tanti
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/arindam-tanti
    - icon: material/book-open-page-variant
      link: https://i-am-ghost.github.io/TuxTechBlogs/
  analytics:
    provider: google
    property: G-BCZ32RGHJ0

# extra_css:
#   - css/extra.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.7/dist/contrib/auto-render.min.js

# Extensions
markdown_extensions:
  - toc:
      permalink: false
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx.table
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true

# Plugins
plugins:
  - search:
      lang:
        - en

spec:
  source: 
    git:
      ref: TuxTechLab
      url: https://github.com/TuxTechLab/Blogs
