# Project information
site_name: Blog.TuxTechLab.com
site_description: Documenting Everything related to Computers, Internet, Security, Software Engineering
site_url: https://github.com/TuxTechLab/Blogs
site_author: Arindam Tanti

# Repository
repo_name: TuxTechLab/Blogs
repo_url: https://github.com/TuxTechLab/Blogs
edit_uri: ''

# Copyright
copyright: Copyright &copy; <a href="http://github.com/TuxTechLab">TuxTechLab</a> 2024 - 2025

# Configuration
theme:
    language: en
    name: material
    highlightjs: true
    hljs_languages:
      - yaml
      - rust
      - html
      - python
      - css
      - c++
      - c
      - javascript
    shortcuts:
        help: 191    # ASCII - ? - HELP
        next: 78     # ASCII - n - NEXT
        previous: 80 # ASCII - p - PREVIOUS
        search: 83   # ASCII - s - SEARCH
    logo: img/logo.png
    favicon: img/favicon.ico
    # Over riding the default font
    font:
      text: Readex Pro
      code: Source Code Pro
    icon:
      logo: fontawesome/solid/code
      repo: fontawesome/brands/github
    features:
      - navigation.top
      - navigation.footer
      - navigation.expand
      - navigation.instant
      - navigation.instant.preview
      - navigation.instant.progress
      - search.suggest
      - search.highlight
      - content.code.copy
    palette:
      # Light mode
      - media: '(prefers-color-scheme: light)'
        scheme: default
        primary: yellow
        accent: amber
        toggle:
          icon: material/weather-night
          name: Dark Mode
      # Dark mode
      - media: '(prefers-color-scheme: dark)'
        scheme: slate
        primary: yellow
        accent: amber
        toggle:
          icon: material/weather-sunny
          name: Light Mode

nav:
  - Start: index.md
  - Code Of Conduct: CODE_OF_CONDUCT.md
  - Contribution Guide: Contribution.md
  - Agile:
    - Introduction To Agile: topic/1.0. Agile/00. Introduction.md
    - Understanding the four values of agile: topic/1.0. Agile/01. Understanding the four values of agile.md
    - Using agile in everyday work: topic/1.0. Agile/02. Using agile in everyday work.md
  - ITSM:
    - Introduction To ITSM: topic/9.0. ITSM/00. Introduction.md
    - Key Terms: topic/9.0. ITSM/01. Key Terms.md
    - ITSM Library and Practices: topic/9.0. ITSM/02. ITSM Library and Practices.md
    - Core ITSM Practices: topic/9.0. ITSM/03. Core ITSM Practices.md
    - Maturity Matters: topic/9.0. ITSM/04. Maturity Matters.md
    - The Atlassian ITSM Solution: topic/9.0. ITSM/05. The Atlassian ITSM Solution.md
    - Key Takeaways: topic/9.0. ITSM/06. Key Takeaways.md
  - Kanban:
    - Introduction To Kanban: topic/11.0. Kanban/00. Introduction.md
    - Kanban Using Jira: topic/11.0. Kanban/01. Kanban Using Jira.md
  - Scrum:
    - Introduction To Scrum: topic/19.0. Scrum/00. Introduction.md
    - Scrum With Jira: topic/19.0. Scrum/01. Scrum With Jira.md
  - Management:
    - Run Effective Meetings:
      - Planning A Productive Meeting: topic/13.1. Management/00. Run Effective Meetings/01. Introduction.md
      - Event Determination: topic/13.1. Management/00. Run Effective Meetings/02. Event Determination.md
      - Running Effective Meeting: topic/13.1. Management/00. Run Effective Meetings/03. Running Effective Meeting.md
      - Preparation: topic/13.1. Management/00. Run Effective Meetings/04. Preparation.md
      - Facilitation: topic/13.1. Management/00. Run Effective Meetings/05. Facilitation.md
      - Participation: topic/13.1. Management/00. Run Effective Meetings/06. Participation.md
      - Follow-up: topic/13.1. Management/00. Run Effective Meetings/07. Follow-up.md
  - Miscellaneous:
    - Acronyms: topic/acronym.md
    - Ports: topic/ports.md
    - Status Codes: topic/status_codes.md


# Customization   
extra:
  consent:
    title: Cookie consent
    description:
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  social:
    - icon: fontawesome/brands/github
      link: https://github.sprcom/tuxtechlab
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/arindam_tanti
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/tuxtechlab
    - icon: material/book-open-page-variant
      link: https://github.com/TuxTechLab/Blogs
  analytics:
    provider: google
    property: G-BCZ32RGHJ0

extra_css:
  - stylesheet/extra.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.7/dist/contrib/auto-render.min.js

# Extensions
markdown_extensions:
  - toc:
      permalink: false
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx.table
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true

# Plugins
plugins:
  - search:
      lang:
        - en

spec:
  source: 
    git:
      ref: Blogs by TuxTechLab
      url: https://github.com/TuxTechLab/Blogs
